Added support for reconnecting when the broker is not available
logstash-plugins/logstash-input-stomp pull request #18
Opened 2016-09-15 12:54 UTC by Narfi

Dear maintainers,

I ran into a use case where I needed automatic reconnections when the broker becomes unavailable, I noticed that version 3.0.1 of the logstash-input-stomp did not support this completely. So I improved this functionality myself. There was already a feature request to improve reconnecting (#4). Thus I did not create a new issue.  However I did change the functionality a little bit, and modified the logging.

I have tested this with ActiveMQ.

Kind regards

2016-09-15 18:17 UTC, wiibaa commented on lib/logstash/inputs/stomp.rb
> +    require "logger"
this is not necessary nor wanted. Logstash plugin inherit the @logger from its base class, 
I suppose you used it for testing but should not be merged in
can you please remove this logger initialisation, please

2016-09-15 18:22 UTC, wiibaa commented on lib/logstash/inputs/stomp.rb
> +    @logger.info("Debug is disabled, turn on debug for full exceptions") if !@debug
Logger level is managed centrally in logstash, so specific debug config in plugin must be deprecated, so this line is not needed

2016-09-15 18:24 UTC, wiibaa requested changes
Thanks for your proposal to improve this plugin.
Can you please address the few comment about logging I mention, also you may need to merge/rebase master in order for the TravisCI to execute properly (travis.yml was outdated)

2016-09-15 19:16 UTC, Narfi commented on lib/logstash/inputs/stomp.rb
> +    require "logger"
Aah I did not know this. I will remove the requirement

2016-09-15 19:21 UTC, Narfi commented on lib/logstash/inputs/stomp.rb
> +    @logger.info("Debug is disabled, turn on debug for full exceptions") if !@debug
Aah I see. I'm relatively new to the Elastic stack. This explains why I wasn't seeing the errors when I was running a command line of the plugin. What is the correct way to displays info messages generated by a plugin? Thanks!

2016-09-16 03:35 UTC, wiibaa commented on lib/logstash/inputs/stomp.rb
> +    @logger.info("Debug is disabled, turn on debug for full exceptions") if !@debug
You can use `--verbose` or `--debug` flags when launching logstash. These flags are mentioned in https://www.elastic.co/guide/en/logstash/current/command-line-flags.html

2016-09-16 09:22 UTC, Narfi commented on lib/logstash/inputs/stomp.rb
> +    @logger.info("Debug is disabled, turn on debug for full exceptions") if !@debug
Thanks for the information. I played around a little with the --verbose and --debug flags. And adjusted the logging accordingly.

2016-10-11 19:43 UTC, suyograo commented
LGTM

2016-10-11 19:43 UTC, merged